### ISSUE TITLE
Column header in main table shows internal name

### ISSUE THREAD

**Issue by pln-rec** [tiuub/PasswordChangeReminder#1]
Hello!

Thanks for this great plugin!
I installed it in KeePass 2.47 (64 bit) and in the main table it shows an internal variable name (as it seems) instead of the right column header as shown on the documentation page. I'm unsure if this is a functional problem though, maybe it's only a cosmetic one.

![image](https://user-images.githubusercontent.com/19349975/115201603-cf488480-a0f5-11eb-9a29-af48c52bff19.png)

**Comment by tiuub** [comment]
Thank you for reporting this bug. 
I will fix this soon. I think I will release the update tomorrow.

**Comment by tiuub** [comment]
Hello,
I have thought about your issue. The plugin is working fine. 
So I think you have chosen the wrong column. To select the right column, click on View -> Configure Columns -> (Scroll down until "Provided by Plugins") -> Select "Renew Password in".

![Screenshot 2021-04-22 145422](https://user-images.githubusercontent.com/46517077/115717959-fb286c00-a37a-11eb-8a8e-d5f743313292.jpg)

**Comment by pln-rec** [comment]
Hi!
You are right, the plugin is working fine if one is using it correctly. I was just thinking because in the README.md, _pcr_remindindays_ is shown in the "Edit Entry" screenshot, this would be the right name to chose to activate the column.

Thank you.
