### ISSUE TITLE
Password Change Reminder blocks Autotype with invisible window

### ISSUE THREAD

**Issue by Lichtschalter-5000** [tiuub/PasswordChangeReminder#2]
I got an entry which I am being reminded of.
When KeePass is locked and I use the hotkey for starting the autotype, the usual password prompt opens. After filling in the password, Auto Type doesn't start. 
A new window opens: "Password Change Reminder - Overview", but I can't un-minify it. Only after closing this window, Auto Type will start filling out the form. 
When I open KeePass, the overview window pops up as intended.

**Comment by tiuub** [comment]
Hi @Lichtschalter-5000,

seems like a nasty bug. I will get my eyes on it. My first thoughts are, to close the window, when KeePass locks.
I will notify you, when I have a fix for you. Please stay patient.

Kind regards

**Comment by tiuub** [comment]
Hi @Lichtschalter-5000,

sorry for my late answer. The last weeks were very stressful.
I fixed your issue with the newest version 1.2.0. It shouldn't happen again.

Kind regards
tiuub
